# Generated by Django 4.2.2 on 2023-09-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='wish_slug',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='list_slug',
        ),
    ]
