# Generated by Django 4.2.3 on 2023-09-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_wish_wish_slug_remove_wishlist_list_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/wishes'),
        ),
    ]
