# Generated by Django 4.2.3 on 2023-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_wish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/wishes'),
        ),
    ]
