# Generated by Django 4.2.3 on 2023-08-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_user_alter_wish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_field',
            field=models.ImageField(default='images/profile_default.png', upload_to='images/users_profile/'),
        ),
    ]
